name: horizon_routing
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/dCastillo727/flutter_web_manager
repository: https://github.com/dCastillo727/flutter_web_manager.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
